//
//  PaintStyle.swift
//  SmartArt
//
//  Created by jackychoi on 3/1/2024.
//

import Foundation
import SwiftUI

struct PaintStyle: Identifiable{
    let paintStyleImage: String
    let paintStyleName: String
    let examplePaint1: String
    let examplePaint2: String
    let examplePaint3: String
    let examplePaint4: String
    let paintStyleDetail: String
    let id = UUID()
}

let PaintStyleArray = [
    PaintStyle(paintStyleImage: "waterColor", paintStyleName: "Watercolor painting", examplePaint1: "waterColor1", examplePaint2: "waterColor2", examplePaint3: "waterColor3", examplePaint4: "waterColor4", paintStyleDetail: "Watercolor or watercolour, also aquarelle is a painting method in which the paints are made of pigments suspended in a water-based solution. Watercolor refers to both the medium and the resulting artwork. The conventional and most common support — material to which the paint is applied—for watercolor paintings is watercolor paper. Other supports or substrates include stone, ivory, silk, reed, papyrus, bark papers, plastics, vellum, leather, fabric, wood, and watercolor canvas (coated with a gesso that is specially formulated for use with watercolors). Watercolor paper is often made entirely or partially with cotton. This gives the surface the appropriate texture and minimizes distortion when wet. Watercolor papers are usually cold-pressed papers that provide better texture and appearance with a weight at least 300 gsm. Under 300 gsm is commonly not recommended for anything but sketching. Transparency is the main characteristic of watercolors. Watercolors can also be made opaque by adding Chinese white. This is not a method to be used in true watercolor (traditional). Watercolor paint is an ancient form of painting, if not the most ancient form of art itself. In East Asia, watercolor painting with inks is referred to as brush painting or scroll painting. In Chinese, Korean and Japanese painting it has been the dominant medium, often in monochrome black or browns, often using inkstick or other pigments. India, Ethiopia and other countries have long watercolor painting traditions as well."),
    PaintStyle(paintStyleImage: "oilPaint", paintStyleName: "Oil painting", examplePaint1: "oilPaint1", examplePaint2: "oilPaint2", examplePaint3: "oilPaint3", examplePaint4: "oilPaint4", paintStyleDetail: "Oil painting is the process of painting with pigments with a medium of drying oil as the binder. It has been the most common technique for artistic painting on canvas, wood panel or copper for several centuries, spreading from Europe to the rest of the world. The advantages of oil for painting images include greater flexibility, richer and denser colour, the use of layers, and a wider range from light to dark. But the process is slower, especially when one layer of paint needs to be allowed to dry before another is applied. The oldest known oil paintings were created by Buddhist artists in Afghanistan and date back to the 7th century AD. Oil paint was used by Europeans for painting statues and woodwork from at least the 12th century, but its common use for painted images began with Early Netherlandish painting in Northern Europe, and by the height of the Renaissance, oil painting techniques had almost completely replaced the use of egg tempera paints for panel paintings in most of Europe, though not for Orthodox icons or wall paintings, where tempera and fresco, respectively, remained the usual choice. Commonly used drying oils include linseed oil, poppy seed oil, walnut oil, and safflower oil. The choice of oil imparts a range of properties to the paint, such as the amount of yellowing or drying time. The paint could be thinned with turpentine. Certain differences, depending on the oil, are also visible in the sheen of the paints. An artist might use several different oils in the same painting depending on specific pigments and effects desired. The paints themselves also develop a particular consistency depending on the medium. The oil may be boiled with a resin, such as pine resin or frankincense, to create a varnish prized for its body and gloss. The paint itself can be molded into different textures depending on its plasticity."),
    PaintStyle(paintStyleImage: "gouache", paintStyleName: "Gouache", examplePaint1: "gouache1", examplePaint2: "gouache2", examplePaint3: "gouache3", examplePaint4: "gouache4", paintStyleDetail: "Gouache, body color, or opaque watercolor is a water-medium paint consisting of natural pigment, water, a binding agent (usually gum arabic or dextrin), and sometimes additional inert material. Gouache is designed to be opaque. Gouache has a long history, having been used for at least twelve centuries. It is used most consistently by commercial artists for posters, illustrations, comics, and other design work. Gouache is similar to watercolor in that it can be rewetted and dried to a matte finish, and the paint can become infused into its paper support. It is similar to acrylic or oil paints in that it is normally used in an opaque painting style and it can form a superficial layer. Many manufacturers of watercolor paints also produce gouache, and the two can easily be used together."),
    PaintStyle(paintStyleImage: "inkWashPaint", paintStyleName: "Ink wash painting", examplePaint1: "inkWashPaint1", examplePaint2: "inkWashPaint2", examplePaint3: "inkWashPaint3", examplePaint4: "inkWashPaint4", paintStyleDetail: "Ink wash painting is a type of Chinese ink brush painting which uses washes of black ink, such as that used in East Asian calligraphy, in different concentrations. It emerged during the Tang dynasty of China (618–907), and overturned earlier, more realistic techniques. It is typically monochrome, using only shades of black, with a great emphasis on virtuoso brushwork and conveying the perceived spirit or essence of a subject over direct imitation. Ink wash painting flourished from the Song dynasty in China (960–1279) onwards, as well as in Japan after it was introduced by Zen Buddhist monks in the 14th century. Some Western scholars divide Chinese painting (including ink wash painting) into three periods: times of representation, times of expression, and historical Oriental art. Chinese scholars have their own views which may be different; they believe that contemporary Chinese ink wash paintings are the pluralistic continuation of multiple historical traditions. In China, Japan and, to a lesser extent, Korea, ink wash painting formed a distinct stylistic tradition with a different set of artists working in it than from those in other types of painting. In China especially it was a gentlemanly occupation associated with poetry and calligraphy. It was often produced by the scholar-official or literati class, ideally illustrating their own poetry and producing the paintings as gifts for friends or patrons, rather than painting for payment."),
    PaintStyle(paintStyleImage: "charcoal", paintStyleName: "Charcoal", examplePaint1: "charcoal1", examplePaint2: "charcoal2", examplePaint3: "charcoal3", examplePaint4: "charcoal4", paintStyleDetail: "Charcoal pencil, also known as charcoal pencil, is a drawing tool commonly used in sketching and sketching. Drawings made with charcoal are called charcoal drawings. Charcoal pencils are similar in appearance to pencils, but their charcoal cores are generally made from fine tree branches or compressed after firing. Charcoal pencils usually come in two colors: black and brown, and come in three types: hard, medium and soft. Compared with ordinary graphite-core pencils, charcoal pencils are non-reflective, warm in tone, and have strong contrast. But charcoal is relatively sluggish to use, while pencil is smoother. Charcoal also has poor adhesion, and handwriting is generally not easy to be completely erased. Charcoal pencils are generally not mixed with pencils because pencils reflect light while charcoal absorbs light, there are different tones, and it is difficult for their writings to cover each other. But it can be mixed with charcoal strips and charcoal powder.")
]
